language: node_js
node_js:
  - "10"
deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
install:
  - npm install -g serverless
  - travis_retry npm install
script:
  - serverless deploy -s ${STAGE_NAME}
environments:
  - &PRODUCTION_ENV
    - AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY},
    - AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY},
    - TWITTER_CONSUMER_KEY = ${TWITTER_CONSUMER_KEY},
    - TWITTER_CONSUMER_SECRET = ${TWITTER_CONSUMER_SECRET},
    - TWITTER_ACCESS_TOKEN_KEY = ${TWITTER_ACCESS_TOKEN_KEY},
    - TWITTER_ACCESS_TOKEN_SECRET = ${TWITTER_ACCESS_TOKEN_SECRET},
    - TWILIO_ACCOUNT_SID = ${TWILIO_ACCOUNT_SID},
    - TWILIO_AUTH_TOKEN = ${TWILIO_AUTH_TOKEN},
    - SENDGRID_API_KEY = ${SENDGRID_API_KEY}
jobs:
  include:
    # master branch deploys to the 'production' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy twitter-trending"
      if: type = push AND branch = main
      env:
        - STAGE_NAME=production
        - *PRODUCTION_ENV
